ARG SNAPSHOT=""
FROM strongboxci/alpine:base$SNAPSHOT

ENV SBT_VERSION=1.1.6
ENV SBT_HOME="/java/sbt-${SBT_VERSION}"

COPY common-scripts /scripts

USER root

RUN set -x \
 && /scripts/setup-sbt.sh \
 && rm -rf /tmp/* /scripts

USER jenkins
